
before:
  hooks:
    - go mod download
    - go generate ./...
builds:
- id: smallbox
  binary: smallbox
  main: ./cmd/smallbox/main.go
  goos:
    - linux
  goarch:
    - amd64
- env:
  - CGO_ENABLED=0
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
