env:
  - GO111MODULE=on
  - CGO_ENABLED=0

before:
  hooks:
    - go mod download
    - go generate ./...

builds:
- id: smallbox
  binary: smallbox
  main: ./cmd/smallbox/main.go
  goos:
    - linux
  goarch:
    - amd64
archives:
- replacements:
    darwin: Darwin
    linux: Linux
    windows: Windows
    386: i386
    amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
